### ISSUE TITLE
Changing lng and lat at runtime in Vanilla JS

### ISSUE THREAD

**Issue by ChristianWeyer** [fluster/web-google-maps#1]
Do you have an example of how to change lng and lat in Vanilla JS based on values in input fields? 
Thanks.

**Comment by ChristianWeyer** [comment]
Seems attributeChangedCallback is not implemented...?

**Comment by peterpeterparker** [comment]
Hi @ChristianWeyer 

I didn't had the requirements to be able to modify on the fly the position of the center or the markers, therefore, that's probably why it isn't possible yet.

If your goal is to modify lat and long on the fly, then it probably needs a Watch on these property to set a new `setCenter` on the map

If the goal is to add some more or less markers, then it probably needs a new watch on such property to redraw these

But just some spontaneous ideas...

**Comment by ChristianWeyer** [comment]
Makes sense, thanks.

**Comment by peterpeterparker** [comment]
Btw. I'm not against this idea at all @ChristianWeyer
If you would like to extend the component and provide a PR I'm of course happy to assist and help!

Have a good weekend
